[build]
publish = "public/"

[[redirects]]
from = "/"
to = "/en"
status = 301

[[redirects]]
from = "/"
to = "/de"
status = 301
conditions = {Language = ["de"]}

[[redirects]]
from = "/"
to = "/vi"
status = 301
conditions = {Language = ["vi"]}
